server:
  #Eureka默认走的端口
  port: 8761

#应用名称
spring:
  application:
    name: cloud for eureka1


eureka:
  client:
    #配置其他Eureka地址(写法一：http://IP:PORT/eureka;写法二：http://实例主机名称:PORT/eureka)
    service-url:
      defaultZone: http://eureka-cluster1:8761/eureka/,http://eureka-cluster2:8761/eureka/

  #实例名称(可用于简化defaultZone的IP写法)
  #使用该方式在Linux下需要修改/etc/hosts相同的[IP 实例名称]。
  instance:
    hostname: eureka-cluster1

  #关闭自我保护
  server:
    enable-self-preservation: false
    #节点缓存清理
    eviction-interval-timer-in-ms: 60000


