#运行端口
server:
  port: 81

#配置应用名称
spring:
  application:
    name: cloud application ribbon

#指定注册中心地址
eureka:
  client:
    service-url:
      defaultZone: http://192.168.82.1:8761/eureka/ #http://eureka-cluster1:8761/eureka/,http://eureka-cluster2:8761/eureka/