server:
  port: 8080

spring:
  application:
    name: cloud-config-server
    #远程仓库配置
  cloud:
    config:
      server:
        git:
#          username: *
#          password: *
          uri: https://github.com/SmartXiaoLan/cloud-config.git
          #如果有目录则使用下面的参数
#          search-paths:

eureka:
  client:
    service-url:
      defaultZone: http://192.168.82.1:80/eureka/