server:
  port: 8080

#自定义参数
custom:
  serviceName: hystrixProvider


eureka:
  client:
    service-url:
      defaultZone: http://localhost:80/eureka/


spring:
  application:
    name: HystrixOpenFeignConsumerClient

#服务降级
ribbon:
  #请求连接的超时时间，单位MS，默认时间1S
  ConnectTimeout: 1000
  #请求处理的超时时间，单位MS，默认时间1S
  ReadTimeout: 1000

#<<<<<<<<<<<<<<<<<<<<<<>>>>>>>>>>>>>>>>>>>>>>
#Feign默认导入Hystrix，但需要手动开启Feign中的Hystrix
feign:
  hystrix:
    enabled: true
#hystrix服务降级
hystrix:
#  仪表盘接受跨域的域名
  dashboard:
    proxy-stream-allow-list:
      - 127.0.0.1
      - localhost
  command:
    default:
      excution:
        timeout:
          #该属性如果为False则交由Ribbon控制
          enabled: true
        isolation:
          thread:
            #超时熔断时间
            timeoutInMilliseconds: 1000

      #开启远程调用失败或请求被拒的回调。
      fallback:
        enabled: true
      #熔断配置
      #HystrixPropertiesManager可以找到所有的可配置属性
      #与hystrix-consumer项目的配置参数功能是一样的
      circutBreaker:
        enabled: true
        requestVolumThreshold: 20
        errorThresholdPercentage: 50
        sleepWindowInMilliseconds: 5000
        forceOpen: false
        forceClosed: false

#开启actuator监控路径默认开启前两个，hystrix.stream需要手动配置。*表示开启所有。详见SpringBootActuator
#配置完后需要去启动类加注解
#访问路径http://ip:port/actuator/XXX[SpringBoot]
#Hystrix可视化界面访问路劲http://ip:port/hystrix
management:
  endpoints:
    web:
      exposure:
        include:
          - info
          - health
          - hystrix.stream