server:
  port: 8080
  #全局的GZIP压缩
  compression:
    enabled: true
    min-response-size: 512
    mime-types: '*/*'



#自定义参数
custom:
  serviceName: OpenFeignApplicationService


eureka:
  client:
    service-url:
      defaultZone: http://localhost:80/eureka/


spring:
  application:
    name: OpenFeignConsumerClient



#OpenFeign性能优化(局部。消息消费方->消息提供方)
feign:
  compression:
    request:
      #开启请求GZIP
      enabled: true
      #设置支持GZIP压缩的MIME类型，即请求/响应类型
      mime-types:
        - text/xml
        - application/xml
        - application/json
      #启动压缩数据最小阈值，单位字节。默认2048
      min-request-size: 512
    #响应开启GZIP
    response:
      enabled: true

ribbon:
  #请求连接的超时时间，单位MS，默认时间1S
  ConnectTimeout: 1000
  #请求处理的超时时间，单位MS，默认时间1S
  ReadTimeout: 1000

#设置负载均衡策略
application-service:
  ribbon:
    NFLoadBalanceRuleClassName: com.netflix.loadbalancer.RandomRule
