#运行端口
server:
  port: 90

#配置应用名称
spring:
  application:
    name: cloud application ribbon client

#指定注册中心地址
eureka:
  client:
    service-url:
      defaultZone: http://192.168.82.1:8761/eureka/ #http://eureka-cluster1:8761/eureka/,http://eureka-cluster2:8761/eureka/


#设置负载均衡策略
##########第一个键为服务提供放的名称##########
#cloud application ribbon:
#  ribbon:
#    #给定全类名即可
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule


#点对点直连配置
##########第一个键为服务提供放的名称##########
#cloud application ribbon:
#  ribbon:
#    listOfServers: localhost:80,localhost:81
#点对点直连配置关闭Eureka-Server注册功能
#ribbon:
#  eureka:
#    enabled: false
